# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "aws-training-vutch"
    dynamodb_table = "tf-locks"
    encrypt        = true
    key            = "./output/terraform.tfstate"
    region         = "ap-southeast-1"
  }
}
